CREATE DATABASE zhaoshang;
USE zhaoshang;
CREATE TABLE customer(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50),
gender VARCHAR(10),
phone VARCHAR(50),
wechat VARCHAR(100),
whatsapp VARCHAR(100),
type VARCHAR(50),
product VARCHAR(200),
status VARCHAR(50) DEFAULT '新客户',
create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE admin(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50),
password VARCHAR(50)
);
INSERT INTO admin(username,password) VALUES('admin','123456');